<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skipped="4" tests="461" time="3.996"><testcase classname="valid8.base" file="valid8/base.py" line="596" name="valid8.base.as_failure_raiser" time="0.010"></testcase><testcase classname="valid8.base" file="valid8/base.py" line="484" name="valid8.base.failure_raiser" time="0.005"></testcase><testcase classname="valid8.common_syntax" file="valid8/common_syntax.py" line="72" name="valid8.common_syntax.make_validation_func_callable" time="0.004"></testcase><testcase classname="valid8.common_syntax" file="valid8/common_syntax.py" line="25" name="valid8.common_syntax.make_validation_func_callables" time="0.003"><skipped message="doctest skipped for old python versions" type="pytest.skip">&lt;doctest valid8.common_syntax.make_validation_func_callables[1]&gt;:2: doctest skipped for old python versions</skipped></testcase><testcase classname="valid8.entry_points_inline" file="valid8/entry_points_inline.py" line="151" name="valid8.entry_points_inline.validate" time="0.004"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_builtin_func]" time="0.009"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_builtin_inst_method]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_user_function]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partialized_builtin_function]" time="0.003"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partialized_builtin_class_method]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partial_user_function_positional]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partial_user_function_keyword]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partial_user_function_both]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partial_user_function_both_defaults]" time="0.003"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[case_partial_user_function_both_defaults2]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_inst_method_newstyle=False]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_inst_method_newstyle=True]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_unbound_inst_method_newstyle=False]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_unbound_inst_method_newstyle=True]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_class_method_newstyle=False]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_class_method_newstyle=True]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_unbound_class_method_newstyle=False]" time="0.003"><skipped message="Unbound class methods are Not supported in this version of python" type="pytest.skip">/home/travis/build/smarie/python-valid8/valid8/tests/test_base.py:127: Unbound class methods are Not supported in this version of python</skipped></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_unbound_class_method_newstyle=True]" time="0.003"><skipped message="Unbound class methods are Not supported in this version of python" type="pytest.skip">/home/travis/build/smarie/python-valid8/valid8/tests/test_base.py:127: Unbound class methods are Not supported in this version of python</skipped></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_static_method_newstyle=False]" time="0.002"></testcase><testcase classname="valid8.tests.test_base" file="valid8/tests/test_base.py" line="133" name="test_getfullargspec[user_static_method_newstyle=True]" time="0.002"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="7" name="test_empty_validators_list" time="0.001"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="14" name="test_either_single_list_or_several_items" time="0.002"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="21" name="test_list_implicit_and" time="0.002"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="27" name="test_not_not_all" time="0.003"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="61" name="test_validate_or" time="0.002"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="91" name="test_validate_xor" time="0.002"></testcase><testcase classname="valid8.tests.test_composition" file="valid8/tests/test_composition.py" line="119" name="test_validate_and" time="0.003"></testcase><testcase classname="valid8.tests.test_entry_points" file="valid8/tests/test_entry_points.py" line="3" name="test_validate_create_manually" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="10" name="test_validate_field" time="0.004"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="56" name="test_validate_field_property" time="0.004"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="107" name="test_validate_field_custom_type" time="0.005"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="148" name="test_validate_attr" time="0.003"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="160" name="test_validate_arg_nominal_builtin_validators" time="0.005"><system-out>hello
hello
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="190" name="test_validate_out" time="0.003"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="207" name="test_validate_nominal_builtin_validators" time="0.004"><system-out>hello
hello
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="237" name="test_validate_custom_validators_basic" time="0.004"><system-out>hello
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="284" name="test_validate_custom_validators_with_exception" time="0.004"><system-out>hello
1
2
3
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="334" name="test_validate_mini_lambda" time="0.003"><system-out>Hello, john your age is 20
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="347" name="test_validate_none_enforce" time="0.020"><system-out>hello
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="371" name="test_validate_none_pytypes" time="0.006"><system-out>hello
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="395" name="test_validate_none_is_allowed" time="0.003"><system-out>hello
hello
</system-out></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="407" name="test_validate_name_error" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="416" name="test_decorate_manually" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_annotations" file="valid8/tests/test_entry_points_annotations.py" line="428" name="test_validate_tracebacks" time="0.003"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="13" name="test_validate_" time="0.004"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="40" name="test_readme_usage_validate__customization" time="0.003"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="75" name="test_validator_context_manager" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="106" name="test_readme_usage_validator_customization" time="0.003"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="143" name="test_validate_tracebacks" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="163" name="test_typos_in_kwargs" time="0.001"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="171" name="test_validate_auto_disable_display" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="193" name="test_numpy_nan" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="202" name="test_numpy_nan_like_lengths" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="236" name="test_empty_not_empty" time="0.002"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="250" name="test_function_setter_name_in_valid8_error_message" time="0.023"></testcase><testcase classname="valid8.tests.test_entry_points_inline" file="valid8/tests/test_entry_points_inline.py" line="258" name="test_enum_isinstance" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_DidNotFail]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_XorTooManySuccess]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_and_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_not_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_not_all]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_AllValidatorsFailed]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_or_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_skip_on_none]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_CompositionFailure]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_AtLeastOneFailed]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_xor_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="21" name="test_named_import[composition_fail_on_none]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_DidNotFail]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_XorTooManySuccess]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_and_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_not_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_not_all]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_AllValidatorsFailed]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_or_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_skip_on_none]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_CompositionFailure]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_AtLeastOneFailed]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_xor_]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging" file="valid8/tests/pkging/test_packaging.py" line="26" name="test_import_from[composition_fail_on_none]" time="0.002"></testcase><testcase classname="valid8.tests.pkging.test_packaging_wildcard" file="valid8/tests/pkging/test_packaging_wildcard.py" line="4" name="test_wild_import" time="0.001"></testcase><testcase classname="valid8.tests.pkging.test_packaging_wildcard" file="valid8/tests/pkging/test_packaging_wildcard.py" line="8" name="test_wild_import_vlib" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_combining" file="valid8/tests/readme/test_readme_combining.py" line="7" name="test_readme_index_combining_enforce" time="0.010"><system-out>Building house... DONE !
Building house... DONE !
</system-out></testcase><testcase classname="valid8.tests.readme.test_readme_combining" file="valid8/tests/readme/test_readme_combining.py" line="16" name="test_readme_index_combining_autoclass" time="0.007"></testcase><testcase classname="valid8.tests.readme.test_readme_combining" file="valid8/tests/readme/test_readme_combining.py" line="49" name="test_readme_index_combining_autoclass_2" time="0.008"></testcase><testcase classname="valid8.tests.readme.test_readme_combining" file="valid8/tests/readme/test_readme_combining.py" line="81" name="test_readme_index_combining_attrs" time="0.004"></testcase><testcase classname="valid8.tests.readme.test_readme_combining" file="valid8/tests/readme/test_readme_combining.py" line="114" name="test_unused_pytypes" time="0.012"><system-out>you did it !
you did it !
</system-out></testcase><testcase classname="valid8.tests.readme.test_readme_combining" file="valid8/tests/readme/test_readme_combining.py" line="144" name="test_readme_combining_checktypes" time="0.001"><skipped message="checktypes does not seem to work on old python versions see https://gitlab.com/yahya-abou-imran/checktypes/issues/2" type="pytest.skip">valid8/tests/readme/test_readme_combining.py:144: checktypes does not seem to work on old python versions see https://gitlab.com/yahya-abou-imran/checktypes/issues/2</skipped></testcase><testcase classname="valid8.tests.readme.test_readme_examples" file="valid8/tests/readme/test_readme_examples.py" line="7" name="test_readme_examples_4" time="0.006"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="6" name="test_readme_index_usage_quick" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="20" name="test_readme_index_usage_quick2" time="0.003"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="47" name="test_readme_usage_validator" time="0.003"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="97" name="test_readme_usage_customization" time="0.003"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="156" name="test_readme_index_usage_basic" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="180" name="test_readme_index_usage_function" time="0.005"><system-out>Building house... DONE !
Building house... DONE !
Building house... DONE !
</system-out></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="227" name="test_readme_index_usage_class_fields" time="0.006"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="262" name="test_testing" time="0.003"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="278" name="test_advanced_composition" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="297" name="test_readme_index_usage_customization" time="0.004"></testcase><testcase classname="valid8.tests.readme.test_readme_index" file="valid8/tests/readme/test_readme_index.py" line="354" name="test_readme_index_usage_composition" time="0.004"></testcase><testcase classname="valid8.tests.readme.test_readme_syntax" file="valid8/tests/readme/test_readme_syntax.py" line="9" name="test_syntax" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_syntax" file="valid8/tests/readme/test_readme_syntax.py" line="22" name="test_syntax2" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_syntax" file="valid8/tests/readme/test_readme_syntax.py" line="38" name="test_syntax_collection" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_syntax" file="valid8/tests/readme/test_readme_syntax.py" line="59" name="test_syntax_dict" time="0.003"></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="10" name="test_tutorial" time="0.003"><system-out>Hello, 21-years-old fella !
Hello, 21-years-old fella !
Hello, 21-years-old fella !
</system-out></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="73" name="test_usage_base_validation_functions" time="0.002"></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="79" name="test_usage_ensure_valid" time="0.005"></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="126" name="test_usage_is_valid" time="0.005"></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="163" name="test_usage_validators" time="0.004"></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="317" name="test_usage_validate_annotation" time="0.003"></testcase><testcase classname="valid8.tests.readme.test_readme_usage" file="valid8/tests/readme/test_readme_usage.py" line="333" name="test_usage_custom_validators" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_builtin-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_builtin-100-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_builtin-foo-TypeError]" time="0.004"><system-out>Error validating input [x=foo] for function [my_function]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;greater_than_0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_builtin-1.0-TypeError]" time="0.004"><system-out>Error validating input [x=1.0] for function [my_function]. At least one validation function failed for value 1.0. Successes: [&apos;greater_than_0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_builtin--1-ValueError]" time="0.003"><system-out>Error validating input [x=-1] for function [my_function]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;greater_than_0&apos;: &apos;TooSmall: x &gt;= 0 does not hold for x=-1.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[with_validator-0-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[with_validator-100-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[with_validator-foo-TypeError]" time="0.003"><system-out>Error validating [x=foo]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;. Wrong value: &apos;foo&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[with_validator-1.0-TypeError]" time="0.003"><system-out>Error validating [x=1.0]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;. Wrong value: 1.0.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[with_validator--1-ValueError]" time="0.003"><system-out>Error validating [x=-1]. InvalidValue: Function [v.alid = x &gt;= 0] returned [False] for value -1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_builtin-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_builtin-100-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_builtin-foo-TypeError]" time="0.004"><system-out>Error validating output of function [my_function2]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;greater_than_0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_builtin-1.0-TypeError]" time="0.004"><system-out>Error validating output of function [my_function2]. At least one validation function failed for value 1.0. Successes: [&apos;greater_than_0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_builtin--1-ValueError]" time="0.004"><system-out>Error validating output of function [my_function2]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;greater_than_0&apos;: &apos;TooSmall: x &gt;= 0 does not hold for x=-1.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_mini_lambda-0-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_mini_lambda-100-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_mini_lambda-foo-TypeError]" time="0.004"><system-out>Error validating field [x=foo] for class [Foo]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;x &gt;= 0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_mini_lambda-1.0-TypeError]" time="0.004"><system-out>Error validating field [x=1.0] for class [Foo]. At least one validation function failed for value 1.0. Successes: [&apos;x &gt;= 0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_mini_lambda--1-ValueError]" time="0.004"><system-out>Error validating field [x=-1] for class [Foo]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;x &gt;= 0&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_mini_lambda-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_mini_lambda-100-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_mini_lambda-foo-TypeError]" time="0.004"><system-out>Error validating input [x=foo] for function [my_function]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;x &gt;= 0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_mini_lambda-1.0-TypeError]" time="0.004"><system-out>Error validating input [x=1.0] for function [my_function]. At least one validation function failed for value 1.0. Successes: [&apos;x &gt;= 0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_input_mini_lambda--1-ValueError]" time="0.004"><system-out>Error validating input [x=-1] for function [my_function]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;x &gt;= 0&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_mini_lambda-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_mini_lambda-100-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_mini_lambda-foo-TypeError]" time="0.004"><system-out>Error validating input [x=foo] for function [my_function3]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;x &gt;= 0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_mini_lambda-1.0-TypeError]" time="0.005"><system-out>Error validating input [x=1.0] for function [my_function3]. At least one validation function failed for value 1.0. Successes: [&apos;x &gt;= 0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_mini_lambda--1-ValueError]" time="0.004"><system-out>Error validating input [x=-1] for function [my_function3]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;x &gt;= 0&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_mini_lambda-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_mini_lambda-100-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_mini_lambda-foo-TypeError]" time="0.004"><system-out>Error validating output of function [my_function2]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;x &gt;= 0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_mini_lambda-1.0-TypeError]" time="0.004"><system-out>Error validating output of function [my_function2]. At least one validation function failed for value 1.0. Successes: [&apos;x &gt;= 0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_output_mini_lambda--1-ValueError]" time="0.004"><system-out>Error validating output of function [my_function2]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;x &gt;= 0&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_builtin_stdlib-0-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_builtin_stdlib-100-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_builtin_stdlib-foo-TypeError]" time="0.004"><system-out>Error validating field [x=foo] for class [Foo]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;greater_than_0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_builtin_stdlib-1.0-TypeError]" time="0.004"><system-out>Error validating field [x=1.0] for class [Foo]. At least one validation function failed for value 1.0. Successes: [&apos;greater_than_0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[class_field_builtin_stdlib--1-ValueError]" time="0.004"><system-out>Error validating field [x=-1] for class [Foo]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;greater_than_0&apos;: &apos;TooSmall: x &gt;= 0 does not hold for x=-1.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[inline_validate-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[inline_validate-100-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[inline_validate-foo-TypeError]" time="0.003"><system-out>Error validating [x=foo]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;. Wrong value: &apos;foo&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[inline_validate-1.0-TypeError]" time="0.002"><system-out>Error validating [x=1.0]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;. Wrong value: 1.0.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[inline_validate--1-ValueError]" time="0.003"><system-out>Error validating [x=-1]. TooSmall: x &gt;= 0 does not hold for x=-1. Wrong value: -1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_builtin-0-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_builtin-100-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_builtin-foo-TypeError]" time="0.004"><system-out>Error validating input [x=foo] for function [my_function3]. At least one validation function failed for value &apos;foo&apos;. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;, &apos;greater_than_0&apos;: &apos;TypeError: unorderable types: str() &gt;= int()&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_builtin-1.0-TypeError]" time="0.004"><system-out>Error validating input [x=1.0] for function [my_function3]. At least one validation function failed for value 1.0. Successes: [&apos;greater_than_0&apos;] / Failures: {&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;numbers.Integral&apos;&gt;.&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example1" file="valid8/tests/readme/examples/test_example1.py" line="23" name="test_example_1[function_io_builtin--1-ValueError]" time="0.004"><system-out>Error validating input [x=-1] for function [my_function3]. At least one validation function failed for value -1. Successes: [&quot;instance_of_&lt;class &apos;numbers.Integral&apos;&gt;&quot;] / Failures: {&apos;greater_than_0&apos;: &apos;TooSmall: x &gt;= 0 does not hold for x=-1.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_3-foo-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_3-foo_123-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_3-1.1-TypeError]" time="0.003"><system-out>Error validating [s=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_3--ValueError]" time="0.003"><system-out>Error validating [s=&apos;&apos;]. TooShort: len(x) &gt;= 1 does not hold for x=. Wrong value: &apos;&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_3-fOO-ValueError]" time="0.003"><system-out>Error validating [s=fOO]. InvalidValue: Function [txt.islower()] returned [False] for value &apos;fOO&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_mini_lambda-foo-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_mini_lambda-foo_123-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_mini_lambda-1.1-TypeError]" time="0.004"><system-out>Error validating input [s=1.1] for function [my_function]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;.&quot;, &apos;len(s) &gt; 0&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &apos;s.islower()&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;islower&apos;&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_mini_lambda--ValueError]" time="0.004"><system-out>Error validating input [s=&apos;&apos;] for function [my_function]. At least one validation function failed for value &apos;&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;] / Failures: {&apos;len(s) &gt; 0&apos;: &apos;Returned False.&apos;, &apos;s.islower()&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_mini_lambda-fOO-ValueError]" time="0.004"><system-out>Error validating input [s=fOO] for function [my_function]. At least one validation function failed for value &apos;fOO&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;, &apos;len(s) &gt; 0&apos;] / Failures: {&apos;s.islower()&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_1-foo-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_1-foo_123-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_1-1.1-TypeError]" time="0.003"><system-out>Error validating [s=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_1--ValueError]" time="0.003"><system-out>Error validating [s=&apos;&apos;]. TooShort: len(x) &gt;= 1 does not hold for x=. Wrong value: &apos;&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_1-fOO-ValueError]" time="0.003"><system-out>Error validating [s=fOO]. NotEqual: x == foo does not hold for x=fOO. Wrong value: &apos;fOO&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[with_validator-foo-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[with_validator-foo_123-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[with_validator-1.1-TypeError]" time="0.003"><system-out>Error validating [s=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[with_validator--ValueError]" time="0.003"><system-out>Error validating [s=&apos;&apos;]. InvalidValue: Function [v.alid = (len(s) &gt; 0) and s.islower()] returned [False] for value &apos;&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[with_validator-fOO-ValueError]" time="0.003"><system-out>Error validating [s=fOO]. InvalidValue: Function [v.alid = (len(s) &gt; 0) and s.islower()] returned [False] for value &apos;fOO&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_builtin_stdlib-foo-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_builtin_stdlib-foo_123-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_builtin_stdlib-1.1-TypeError]" time="0.004"><system-out>Error validating input [s=1.1] for function [my_function]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;.&quot;, &apos;length_greater_than_1&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &apos;islower&apos;: &quot;TypeError: descriptor &apos;islower&apos; requires a &apos;str&apos; object but received a &apos;float&apos;&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_builtin_stdlib--ValueError]" time="0.004"><system-out>Error validating input [s=&apos;&apos;] for function [my_function]. At least one validation function failed for value &apos;&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;] / Failures: {&apos;length_greater_than_1&apos;: &apos;TooShort: len(x) &gt;= 1 does not hold for x=.&apos;, &apos;islower&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[function_input_builtin_stdlib-fOO-ValueError]" time="0.004"><system-out>Error validating input [s=fOO] for function [my_function]. At least one validation function failed for value &apos;fOO&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;, &apos;length_greater_than_1&apos;] / Failures: {&apos;islower&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_mini_lambda-foo-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_mini_lambda-foo_123-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_mini_lambda-1.1-TypeError]" time="0.005"><system-out>Error validating field [s=1.1] for class [Foo]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;.&quot;, &apos;len(s) &gt; 0&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &apos;s.islower()&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;islower&apos;&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_mini_lambda--ValueError]" time="0.004"><system-out>Error validating field [s=] for class [Foo]. At least one validation function failed for value &apos;&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;] / Failures: {&apos;len(s) &gt; 0&apos;: &apos;Returned False.&apos;, &apos;s.islower()&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_mini_lambda-fOO-ValueError]" time="0.004"><system-out>Error validating field [s=fOO] for class [Foo]. At least one validation function failed for value &apos;fOO&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;, &apos;len(s) &gt; 0&apos;] / Failures: {&apos;s.islower()&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_2-foo-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_2-foo_123-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_2-1.1-TypeError]" time="0.003"><system-out>Error validating [s=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_2--ValueError]" time="0.002"><system-out>Error validating [s=&apos;&apos;]. TooShort: len(x) &gt;= 1 does not hold for x=. Wrong value: &apos;&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[inline_validate_2-fOO-ValueError]" time="0.003"><system-out>Error validating [s=fOO]. InvalidValue: Function [islower] returned [False] for value &apos;fOO&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_builtin_stdlib-foo-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_builtin_stdlib-foo_123-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_builtin_stdlib-1.1-TypeError]" time="0.004"><system-out>Error validating field [s=1.1] for class [Foo]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;.&quot;, &apos;length_greater_than_1&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &apos;islower&apos;: &quot;TypeError: descriptor &apos;islower&apos; requires a &apos;str&apos; object but received a &apos;float&apos;&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_builtin_stdlib--ValueError]" time="0.004"><system-out>Error validating field [s=] for class [Foo]. At least one validation function failed for value &apos;&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;] / Failures: {&apos;length_greater_than_1&apos;: &apos;TooShort: len(x) &gt;= 1 does not hold for x=.&apos;, &apos;islower&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="25" name="test_example_2[class_field_builtin_stdlib-fOO-ValueError]" time="0.004"><system-out>Error validating field [s=fOO] for class [Foo]. At least one validation function failed for value &apos;fOO&apos;. Successes: [&quot;instance_of_&lt;class &apos;str&apos;&gt;&quot;, &apos;length_greater_than_1&apos;] / Failures: {&apos;islower&apos;: &apos;Returned False.&apos;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="46" name="test_example_2_regexp[foo@bar.com-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example2" file="valid8/tests/readme/examples/test_example2.py" line="46" name="test_example_2_regexp[a@a@s-ValueError]" time="0.003"><system-out>Error validating [s=a@a@s]. InvalidValue: Function [&lt;lambda&gt;] returned [False] for value &apos;a@a@s&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(0.2, &apos;foo&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(1.0, &apos;abc&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(0, &apos;foo&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidValue: Function [v.alid = len(t) == 2 \] returned [False] for value (0.2, &apos;foo&apos;, True).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Real&apos;&gt;. Wrong value: &apos;1.0&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [v.alid = len(t) == 2 \ ; and instance_of(t[0], Real) and (0 &lt;= t[0] &lt;= 1) \] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>Error validating [t=(1.0, False)]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: False.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [v.alid = len(t) == 2 \ ; and instance_of(t[0], Real) and (0 &lt;= t[0] &lt;= 1) \ ; and instance_of(t[1], str) and len(t[1]) == 3 and t[1].islower()] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_boolean_tester-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [v.alid = len(t) == 2 \ ; and instance_of(t[0], Real) and (0 &lt;= t[0] &lt;= 1) \ ; and instance_of(t[1], str) and len(t[1]) == 3 and t[1].islower()] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(0.2, &apos;foo&apos;)-True]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(1.0, &apos;abc&apos;)-True]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(0, &apos;foo&apos;)-True]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=1.1] for class [Foo]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=(0.2, &apos;foo&apos;, True)] for class [Foo]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.2, &apos;foo&apos;, True).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=(&apos;1.0&apos;, &apos;foo&apos;)] for class [Foo]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Real&apos;&gt;. Wrong value: &apos;1.0&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=(1.1, &apos;foo&apos;)] for class [Foo]. InvalidValue: Function [is_valid_tuple] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=(1.0, False)] for class [Foo]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: False.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=(0.5, &apos;a&apos;)] for class [Foo]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_is_valid_tuple-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func is_valid_tuple
Error validating field [t=(0.5, &apos;AAA&apos;)] for class [Foo]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(0.2, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(1.0, &apos;abc&apos;)-True]" time="0.004"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(0, &apos;foo&apos;)-True]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=1.1] for class [Foo]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=(0.2, &apos;foo&apos;, True)] for class [Foo]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=(&apos;1.0&apos;, &apos;foo&apos;)] for class [Foo]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=(1.1, &apos;foo&apos;)] for class [Foo]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=(1.0, False)] for class [Foo]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=(0.5, &apos;a&apos;)] for class [Foo]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_is_valid_tuple_pep-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function class_fields_custom with custom func ex3_is_valid_tuple_pep
Error validating field [t=(0.5, &apos;AAA&apos;)] for class [Foo]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(0.2, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(1.0, &apos;abc&apos;)-True]" time="0.006"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(0, &apos;foo&apos;)-True]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=1.1] for class [Foo]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.008"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=(0.2, &apos;foo&apos;, True)] for class [Foo]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=(&apos;1.0&apos;, &apos;foo&apos;)] for class [Foo]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=(1.1, &apos;foo&apos;)] for class [Foo]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=(1.0, False)] for class [Foo]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=(0.5, &apos;a&apos;)] for class [Foo]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_ex3_check_valid_tuple_pep-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.007"><system-out>calling function class_fields_custom with custom func ex3_check_valid_tuple_pep
Error validating field [t=(0.5, &apos;AAA&apos;)] for class [Foo]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(0.2, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function class_fields_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(1.0, &apos;abc&apos;)-True]" time="0.005"><system-out>calling function class_fields_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(0, &apos;foo&apos;)-True]" time="0.004"><system-out>calling function class_fields_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=1.1] for class [Foo]. InvalidType: Function [check_valid_tuple] raised TypeError: item should be a tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=(0.2, &apos;foo&apos;, True)] for class [Foo]. InvalidValue: Function [check_valid_tuple] raised ValueError: tuple length should be 2, found (0.2, &apos;foo&apos;, True)
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=(&apos;1.0&apos;, &apos;foo&apos;)] for class [Foo]. InvalidType: Function [check_valid_tuple] raised TypeError: first elt should be a Real, found 1.0
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=(1.1, &apos;foo&apos;)] for class [Foo]. InvalidValue: Function [check_valid_tuple] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=(1.0, False)] for class [Foo]. InvalidType: Function [check_valid_tuple] raised TypeError: second elt should be a string, found False
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=(0.5, &apos;a&apos;)] for class [Foo]. InvalidValue: Function [check_valid_tuple] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_fields_custom_check_valid_tuple-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function class_fields_custom with custom func check_valid_tuple
Error validating field [t=(0.5, &apos;AAA&apos;)] for class [Foo]. InvalidValue: Function [check_valid_tuple] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(0.2, &apos;foo&apos;)-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(1.0, &apos;abc&apos;)-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(0, &apos;foo&apos;)-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>Error validating input [t=1.1] for function [my_function]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;tuple&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;.&quot;, &apos;length_equals_2&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &quot;map_&lt;(and(instance_of_&lt;class &apos;numbers.Real&apos;&gt;, between_0_and_1), and(instance_of_&lt;class &apos;str&apos;&gt;, length_equals_3, islower))&gt;_on_elts&quot;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating input [t=(0.2, &apos;foo&apos;, True)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>Error validating input [t=(&apos;1.0&apos;, &apos;foo&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating input [t=(1.1, &apos;foo&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>Error validating input [t=(1.0, False)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating input [t=(0.5, &apos;a&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_builtin_stdlib-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating input [t=(0.5, &apos;AAA&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(0.2, &apos;foo&apos;)-True]" time="0.005"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(1.0, &apos;abc&apos;)-True]" time="0.005"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(0, &apos;foo&apos;)-True]" time="0.005"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>Error validating field [t=1.1] for class [Foo]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;tuple&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;.&quot;, &apos;len(t) == 2&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &apos;instance_of(t[0], Real)&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;(t[0] &gt;= 0) &amp; (t[0] &lt;= 1)&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;instance_of(t[1], str)&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;len(t[1]) == 3&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;t[1].islower()&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating field [t=(0.2, &apos;foo&apos;, True)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>Error validating field [t=(&apos;1.0&apos;, &apos;foo&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating field [t=(1.1, &apos;foo&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>Error validating field [t=(1.0, False)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating field [t=(0.5, &apos;a&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_mini_lambda-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating field [t=(0.5, &apos;AAA&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(0.2, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(1.0, &apos;abc&apos;)-True]" time="0.002"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(0, &apos;foo&apos;)-True]" time="0.002"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.2, &apos;foo&apos;, True).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Real&apos;&gt;. Wrong value: &apos;1.0&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [is_valid_tuple] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=(1.0, False)]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: False.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_is_valid_tuple-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func is_valid_tuple
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(0.2, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(1.0, &apos;abc&apos;)-True]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(0, &apos;foo&apos;)-True]" time="0.004"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=1.1]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=(1.0, False)]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_is_valid_tuple_pep-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_is_valid_tuple_pep
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(0.2, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(1.0, &apos;abc&apos;)-True]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(0, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=1.1]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=(1.0, False)]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_ex3_check_valid_tuple_pep-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validate_custom with custom func ex3_check_valid_tuple_pep
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(0.2, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(1.0, &apos;abc&apos;)-True]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(0, &apos;foo&apos;)-True]" time="0.002"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=1.1]. InvalidType: Function [check_valid_tuple] raised TypeError: item should be a tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidValue: Function [check_valid_tuple] raised ValueError: tuple length should be 2, found (0.2, &apos;foo&apos;, True)
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [check_valid_tuple] raised TypeError: first elt should be a Real, found 1.0
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [check_valid_tuple] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=(1.0, False)]. InvalidType: Function [check_valid_tuple] raised TypeError: second elt should be a string, found False
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [check_valid_tuple] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_custom_check_valid_tuple-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validate_custom with custom func check_valid_tuple
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [check_valid_tuple] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(0.2, &apos;foo&apos;)-True]" time="0.005"><system-out>uncomment and put your breakpoint here to debug
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(1.0, &apos;abc&apos;)-True]" time="0.005"><system-out>uncomment and put your breakpoint here to debug
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(0, &apos;foo&apos;)-True]" time="0.005"><system-out>uncomment and put your breakpoint here to debug
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=1.1] for function [my_function]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;tuple&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;.&quot;, &apos;len(t) == 2&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &apos;instance_of(t[0], Real)&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;(t[0] &gt;= 0) &amp; (t[0] &lt;= 1)&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;instance_of(t[1], str)&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;len(t[1]) == 3&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;, &apos;t[1].islower()&apos;: &quot;AttributeError: &apos;float&apos; object has no attribute &apos;__getitem__&apos;&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=(0.2, &apos;foo&apos;, True)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=(&apos;1.0&apos;, &apos;foo&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=(1.1, &apos;foo&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=(1.0, False)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=(0.5, &apos;a&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_mini_lambda-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>uncomment and put your breakpoint here to debug
Error validating input [t=(0.5, &apos;AAA&apos;)] for function [my_function]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(0.2, &apos;foo&apos;)-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(1.0, &apos;abc&apos;)-True]" time="0.002"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(0, &apos;foo&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidValue: Function [# the tuple should be of length 2 ; if len(t) != 2: ; raise ValueError(&apos;tuple length should be 2, found &apos; + str(t))] raised ValueError: tuple length should be 2, found (0.2, &apos;foo&apos;, True)
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [# the tuple should be of length 2 ; if len(t) != 2: ; raise ValueError(&apos;tuple length should be 2, found &apos; + str(t)) ;  ; # the first element is a float between 0 and 1 ; if not isinstance(t[0], Real): ; raise TypeError(&apos;first elt should be a Real, found &apos; + str(t[0]))] raised TypeError: first elt should be a Real, found 1.0
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [# the tuple should be of length 2 ; if len(t) != 2: ; raise ValueError(&apos;tuple length should be 2, found &apos; + str(t)) ;  ; # the first element is a float between 0 and 1 ; if not isinstance(t[0], Real): ; raise TypeError(&apos;first elt should be a Real, found &apos; + str(t[0])) ; if not (0 &lt;= t[0] &lt;= 1): ; raise ValueError(&apos;first elt should be between 0 and 1,found &apos; + str(t[0]))] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(1.0, False)]. InvalidType: Function [# the tuple should be of length 2 ; if len(t) != 2: ; raise ValueError(&apos;tuple length should be 2, found &apos; + str(t)) ;  ; # the first element is a float between 0 and 1 ; if not isinstance(t[0], Real): ; raise TypeError(&apos;first elt should be a Real, found &apos; + str(t[0])) ; if not (0 &lt;= t[0] &lt;= 1): ; raise ValueError(&apos;first elt should be between 0 and 1,found &apos; + str(t[0])) ;  ; # the second element is a lowercase string of size 3 ; if not isinstance(t[1], str): ; raise TypeError(&apos;second elt should be a string, found &apos; + str(t[1]))] raised TypeError: second elt should be a string, found False
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [# the tuple should be of length 2 ; if len(t) != 2: ; raise ValueError(&apos;tuple length should be 2, found &apos; + str(t)) ;  ; # the first element is a float between 0 and 1 ; if not isinstance(t[0], Real): ; raise TypeError(&apos;first elt should be a Real, found &apos; + str(t[0])) ; if not (0 &lt;= t[0] &lt;= 1): ; raise ValueError(&apos;first elt should be between 0 and 1,found &apos; + str(t[0])) ;  ; # the second element is a lowercase string of size 3 ; if not isinstance(t[1], str): ; raise TypeError(&apos;second elt should be a string, found &apos; + str(t[1])) ; if not (len(t[1]) == 3 and t[1].islower()): ; raise ValueError(&apos;second elt should be a lowercase string of length 3,&apos; ; &apos;found &apos; + str(t[1]))] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[with_validator_failure_raiser-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [# the tuple should be of length 2 ; if len(t) != 2: ; raise ValueError(&apos;tuple length should be 2, found &apos; + str(t)) ;  ; # the first element is a float between 0 and 1 ; if not isinstance(t[0], Real): ; raise TypeError(&apos;first elt should be a Real, found &apos; + str(t[0])) ; if not (0 &lt;= t[0] &lt;= 1): ; raise ValueError(&apos;first elt should be between 0 and 1,found &apos; + str(t[0])) ;  ; # the second element is a lowercase string of size 3 ; if not isinstance(t[1], str): ; raise TypeError(&apos;second elt should be a string, found &apos; + str(t[1])) ; if not (len(t[1]) == 3 and t[1].islower()): ; raise ValueError(&apos;second elt should be a lowercase string of length 3,&apos; ; &apos;found &apos; + str(t[1]))] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(0.2, &apos;foo&apos;)-True]" time="0.005"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(1.0, &apos;abc&apos;)-True]" time="0.004"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(0, &apos;foo&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>Error validating field [t=1.1] for class [Foo]. At least one validation function failed for value 1.1. Successes: [] / Failures: {&quot;instance_of_&lt;class &apos;tuple&apos;&gt;&quot;: &quot;HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;.&quot;, &apos;length_equals_2&apos;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;, &quot;map_&lt;(and(instance_of_&lt;class &apos;numbers.Real&apos;&gt;, between_0_and_1), and(instance_of_&lt;class &apos;str&apos;&gt;, length_equals_3, islower))&gt;_on_elts&quot;: &quot;TypeError: object of type &apos;float&apos; has no len()&quot;}.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>Error validating field [t=(0.2, &apos;foo&apos;, True)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>Error validating field [t=(&apos;1.0&apos;, &apos;foo&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>Error validating field [t=(1.1, &apos;foo&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>Error validating field [t=(1.0, False)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>Error validating field [t=(0.5, &apos;a&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[class_field_builtin_stdlib-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>Error validating field [t=(0.5, &apos;AAA&apos;)] for class [Foo]. Error while formatting help message: not all arguments converted during string formatting
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(0.2, &apos;foo&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(1.0, &apos;abc&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(0, &apos;foo&apos;)-True]" time="0.003"></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t=(0.2, &apos;foo&apos;, True)]. WrongLength: len(x) == 2 does not hold for x=(0.2, &apos;foo&apos;, True). Wrong value: (0.2, &apos;foo&apos;, True).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t[0]=1.0]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Real&apos;&gt;. Wrong value: &apos;1.0&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t[0]=1.1]. TooBig: x &lt;= 1 does not hold for x=1.1. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>Error validating [t[1]=False]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: False.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t[1]=a]. WrongLength: len(x) == 3 does not hold for x=a. Wrong value: &apos;a&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validate_1-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>Error validating [t[1]=AAA]. InvalidValue: Function [islower] returned [False] for value &apos;AAA&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(0.2, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(1.0, &apos;abc&apos;)-True]" time="0.005"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(0, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=1.1]. InvalidType: Function [custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidType: Function [custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [custom(t)] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=(1.0, False)]. InvalidType: Function [custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [custom(t)] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_ex3_check_valid_tuple_pep_raiser-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function inline_validation_custom_raiser with custom func ex3_check_valid_tuple_pep
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [custom(t)] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(0.2, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(1.0, &apos;abc&apos;)-True]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(0, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=1.1]. InvalidType: Function [custom(t)] raised TypeError: item should be a tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidValue: Function [custom(t)] raised ValueError: tuple length should be 2, found (0.2, &apos;foo&apos;, True)
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [custom(t)] raised TypeError: first elt should be a Real, found 1.0
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [custom(t)] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=(1.0, False)]. InvalidType: Function [custom(t)] raised TypeError: second elt should be a string, found False
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [custom(t)] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validation_custom_check_valid_tuple_raiser-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validation_custom_raiser with custom func check_valid_tuple
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [custom(t)] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(0.2, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function function_input_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(1.0, &apos;abc&apos;)-True]" time="0.004"><system-out>calling function function_input_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(0, &apos;foo&apos;)-True]" time="0.002"><system-out>calling function function_input_custom with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=1.1] for function [my_function]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=(0.2, &apos;foo&apos;, True)] for function [my_function]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.2, &apos;foo&apos;, True).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=(&apos;1.0&apos;, &apos;foo&apos;)] for function [my_function]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Real&apos;&gt;. Wrong value: &apos;1.0&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=(1.1, &apos;foo&apos;)] for function [my_function]. InvalidValue: Function [is_valid_tuple] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=(1.0, False)] for function [my_function]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: False.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=(0.5, &apos;a&apos;)] for function [my_function]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_is_valid_tuple-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function function_input_custom with custom func is_valid_tuple
Error validating input [t=(0.5, &apos;AAA&apos;)] for function [my_function]. InvalidValue: Function [is_valid_tuple] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(0.2, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(1.0, &apos;abc&apos;)-True]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(0, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=1.1] for function [my_function]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=(0.2, &apos;foo&apos;, True)] for function [my_function]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=(&apos;1.0&apos;, &apos;foo&apos;)] for function [my_function]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=(1.1, &apos;foo&apos;)] for function [my_function]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=(1.0, False)] for function [my_function]. InvalidType: Function [ex3_is_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=(0.5, &apos;a&apos;)] for function [my_function]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_is_valid_tuple_pep-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_is_valid_tuple_pep
Error validating input [t=(0.5, &apos;AAA&apos;)] for function [my_function]. InvalidValue: Function [ex3_is_valid_tuple_pep] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(0.2, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(1.0, &apos;abc&apos;)-True]" time="0.005"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(0, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=1.1] for function [my_function]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.007"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=(0.2, &apos;foo&apos;, True)] for function [my_function]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=(&apos;1.0&apos;, &apos;foo&apos;)] for function [my_function]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=(1.1, &apos;foo&apos;)] for function [my_function]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=(1.0, False)] for function [my_function]. InvalidType: Function [ex3_check_valid_tuple_pep] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_check_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=(0.5, &apos;a&apos;)] for function [my_function]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_ex3_check_valid_tuple_pep-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.006"><system-out>calling function function_input_custom with custom func ex3_check_valid_tuple_pep
Error validating input [t=(0.5, &apos;AAA&apos;)] for function [my_function]. InvalidValue: Function [ex3_check_valid_tuple_pep] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(0.2, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function function_input_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(1.0, &apos;abc&apos;)-True]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(0, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function function_input_custom with custom func check_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=1.1] for function [my_function]. InvalidType: Function [check_valid_tuple] raised TypeError: item should be a tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=(0.2, &apos;foo&apos;, True)] for function [my_function]. InvalidValue: Function [check_valid_tuple] raised ValueError: tuple length should be 2, found (0.2, &apos;foo&apos;, True)
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=(&apos;1.0&apos;, &apos;foo&apos;)] for function [my_function]. InvalidType: Function [check_valid_tuple] raised TypeError: first elt should be a Real, found 1.0
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=(1.1, &apos;foo&apos;)] for function [my_function]. InvalidValue: Function [check_valid_tuple] raised ValueError: first elt should be between 0 and 1,found 1.1
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=(1.0, False)] for function [my_function]. InvalidType: Function [check_valid_tuple] raised TypeError: second elt should be a string, found False
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=(0.5, &apos;a&apos;)] for function [my_function]. InvalidValue: Function [check_valid_tuple] raised ValueError: second elt should be a lowercase string of length 3,found a
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[function_input_custom_check_valid_tuple-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.004"><system-out>calling function function_input_custom with custom func check_valid_tuple
Error validating input [t=(0.5, &apos;AAA&apos;)] for function [my_function]. InvalidValue: Function [check_valid_tuple] raised ValueError: second elt should be a lowercase string of length 3,found AAA
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(0.2, &apos;foo&apos;)-True]" time="0.004"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(1.0, &apos;abc&apos;)-True]" time="0.002"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(0, &apos;foo&apos;)-True]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=1.1]. HasWrongType: Value should be an instance of &lt;class &apos;tuple&apos;&gt;. Wrong value: 1.1.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (0.2, &apos;foo&apos;, True).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. HasWrongType: Value should be an instance of &lt;class &apos;numbers.Real&apos;&gt;. Wrong value: &apos;1.0&apos;.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=(1.0, False)]. HasWrongType: Value should be an instance of &lt;class &apos;str&apos;&gt;. Wrong value: False.
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_is_valid_tuple_boolean-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func is_valid_tuple
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(0.2, &apos;foo&apos;)-True]" time="0.006"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(1.0, &apos;abc&apos;)-True]" time="0.005"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(0, &apos;foo&apos;)-True]" time="0.005"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-1.1-&lt;class &apos;TypeError&apos;&gt;]" time="0.005"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=1.1]. InvalidType: Function [v.alid = custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[float]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(0.2, &apos;foo&apos;, True)-&lt;class &apos;ValueError&apos;&gt;]" time="0.003"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=(0.2, &apos;foo&apos;, True)]. InvalidType: Function [v.alid = custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, str, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(&apos;1.0&apos;, &apos;foo&apos;)-&lt;class &apos;TypeError&apos;&gt;]" time="0.004"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=(&apos;1.0&apos;, &apos;foo&apos;)]. InvalidType: Function [v.alid = custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[str, str]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(1.1, &apos;foo&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=(1.1, &apos;foo&apos;)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (1.1, &apos;foo&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(1.0, False)-&lt;class &apos;TypeError&apos;&gt;]" time="0.007"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=(1.0, False)]. InvalidType: Function [v.alid = custom(t)] raised InputTypeError: 
  valid8.tests.readme.examples._tests_pep484.ex3_is_valid_tuple_pep
  called with incompatible types:
Expected: Tuple[Tuple[Real, str]]
Received: Tuple[Tuple[float, bool]]
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(0.5, &apos;a&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=(0.5, &apos;a&apos;)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (0.5, &apos;a&apos;).
</system-out></testcase><testcase classname="valid8.tests.readme.examples.test_example3" file="valid8/tests/readme/examples/test_example3.py" line="49" name="test_example_3[inline_validator_custom_ex3_is_valid_tuple_pep_boolean-(0.5, &apos;AAA&apos;)-&lt;class &apos;ValueError&apos;&gt;]" time="0.005"><system-out>calling function inline_validator_custom_boolean with custom func ex3_is_valid_tuple_pep
Error validating [t=(0.5, &apos;AAA&apos;)]. InvalidValue: Function [v.alid = custom(t)] returned [False] for value (0.5, &apos;AAA&apos;).
</system-out></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="8" name="test_is_in" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="16" name="test_contains" time="0.001"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="23" name="test_is_subset_is_superset" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="46" name="test_on_all" time="0.001"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="55" name="test_on_each" time="0.004"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="64" name="test_haslen" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="71" name="test_minlen" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="78" name="test_maxlen" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="85" name="test_empty" time="0.001"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="92" name="test_nonempty" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="99" name="test_length_between" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_collections" file="valid8/tests/validation_lib/test_validators_collections.py" line="108" name="test_numpy_nan_like_lengths" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_comparables" file="valid8/tests/validation_lib/test_validators_comparables.py" line="5" name="test_gt" time="0.001"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_comparables" file="valid8/tests/validation_lib/test_validators_comparables.py" line="12" name="test_gts" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_comparables" file="valid8/tests/validation_lib/test_validators_comparables.py" line="19" name="test_lt" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_comparables" file="valid8/tests/validation_lib/test_validators_comparables.py" line="26" name="test_lts" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_comparables" file="valid8/tests/validation_lib/test_validators_comparables.py" line="33" name="test_between" time="0.003"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_comparables" file="valid8/tests/validation_lib/test_validators_comparables.py" line="45" name="test_numpy_nan" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_numbers" file="valid8/tests/validation_lib/test_validators_numbers.py" line="5" name="test_is_even" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_numbers" file="valid8/tests/validation_lib/test_validators_numbers.py" line="11" name="test_is_odd" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_numbers" file="valid8/tests/validation_lib/test_validators_numbers.py" line="17" name="test_is_multiple_of" time="0.002"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_types" file="valid8/tests/validation_lib/test_validators_types.py" line="6" name="test_instance_of" time="0.003"></testcase><testcase classname="valid8.tests.validation_lib.test_validators_types" file="valid8/tests/validation_lib/test_validators_types.py" line="32" name="test_subclass_of" time="0.013"></testcase></testsuite>